services:
  tenants-api:
    image: ${DOCKER_IMAGE_TAG}
    container_name: dotcruz-tenants-api
    restart: unless-stopped
    ports:
      - "5052:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - dotcruz_net
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  dotcruz_net:
    name: dotcruz_net
    external: true
