// <auto-generated />
using System;
using DotCruz.Tenants.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotCruz.Tenants.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260716191209_AddTenantBranding")]
    partial class AddTenantBranding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotCruz.Tenants.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("DotCruz.Tenants.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Fiscal.FiscalDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("document_type");

                            b1.HasKey("TenantId");

                            b1.HasIndex("Number")
                                .IsUnique()
                                .HasDatabaseName("ix_tenants_document_number");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenants_tenants_id");
                        });

                    b.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Tenants.TenantAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("TenantId");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasJsonPropertyName("city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasJsonPropertyName("complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasJsonPropertyName("neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasJsonPropertyName("number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasJsonPropertyName("state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasJsonPropertyName("street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasJsonPropertyName("zip_code");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1
                                .ToJson("address")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenants_tenants_id");
                        });

                    b.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Tenants.TenantBranding", "Branding", b1 =>
                        {
                            b1.Property<Guid>("TenantId");

                            b1.Property<string>("HeaderBackgroundColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasJsonPropertyName("header_background_color");

                            b1.Property<string>("LogoUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasJsonPropertyName("logo_url");

                            b1.Property<string>("UnsubscribeUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasJsonPropertyName("unsubscribe_url");

                            b1.Property<string>("Website")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasJsonPropertyName("website");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1
                                .ToJson("branding")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenants_tenants_id");
                        });

                    b.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Tenants.TenantContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("citext")
                                .HasColumnName("contact_email");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenants_tenants_id");

                            b1.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Communication.PhoneNumber", "Phone", b2 =>
                                {
                                    b2.Property<Guid>("TenantContactTenantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("CountryCode")
                                        .HasColumnType("integer")
                                        .HasColumnName("contact_phone_country_code");

                                    b2.Property<string>("NationalNumber")
                                        .IsRequired()
                                        .HasMaxLength(14)
                                        .HasColumnType("character varying(14)")
                                        .HasColumnName("contact_phone_national_number");

                                    b2.HasKey("TenantContactTenantId");

                                    b2.ToTable("tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantContactTenantId")
                                        .HasConstraintName("fk_tenants_tenants_id");
                                });

                            b1.Navigation("Phone")
                                .IsRequired();
                        });

                    b.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Tenants.TenantSubscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Plan")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("subscription_plan");

                            b1.Property<DateTimeOffset?>("TrialEndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_trial_end_date");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenants_tenants_id");

                            b1.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Temporal.DateTimePeriod", "Duration", b2 =>
                                {
                                    b2.Property<Guid>("TenantSubscriptionTenantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("subscription_end_date");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("subscription_start_date");

                                    b2.HasKey("TenantSubscriptionTenantId");

                                    b2.ToTable("tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantSubscriptionTenantId")
                                        .HasConstraintName("fk_tenants_tenants_id");
                                });

                            b1.OwnsOne("DotCruz.Tenants.Domain.ValueObjects.Tenants.ResourceLimits", "Limits", b2 =>
                                {
                                    b2.Property<Guid>("TenantSubscriptionTenantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("MaxEmailsPerMonth")
                                        .HasColumnType("integer")
                                        .HasColumnName("subscription_max_emails_per_month");

                                    b2.Property<int>("MaxUsers")
                                        .HasColumnType("integer")
                                        .HasColumnName("subscription_max_users");

                                    b2.HasKey("TenantSubscriptionTenantId");

                                    b2.ToTable("tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantSubscriptionTenantId")
                                        .HasConstraintName("fk_tenants_tenants_id");
                                });

                            b1.Navigation("Duration")
                                .IsRequired();

                            b1.Navigation("Limits")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Branding")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
