//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotCruz.Tenants.Domain.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotCruz.Tenants.Domain.Exceptions.Resources.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The address is required..
        /// </summary>
        public static string ADDRESS_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The admin user is required.
        /// </summary>
        public static string ADMIN_USER_REQUIRED {
            get {
                return ResourceManager.GetString("ADMIN_USER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The city is required..
        /// </summary>
        public static string CITY_EMPTY {
            get {
                return ResourceManager.GetString("CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The contact is required..
        /// </summary>
        public static string CONTACT_REQUIRED {
            get {
                return ResourceManager.GetString("CONTACT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document number already exists..
        /// </summary>
        public static string DOCUMENT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("DOCUMENT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document number cannot be empty..
        /// </summary>
        public static string DOCUMENT_EMPTY {
            get {
                return ResourceManager.GetString("DOCUMENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document number is invalid..
        /// </summary>
        public static string DOCUMENT_INVALID {
            get {
                return ResourceManager.GetString("DOCUMENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document is required..
        /// </summary>
        public static string DOCUMENT_REQUIRED {
            get {
                return ResourceManager.GetString("DOCUMENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The duration period is required..
        /// </summary>
        public static string DURATION_REQUIRED {
            get {
                return ResourceManager.GetString("DURATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The contact email is required..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The contact email format is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a External integration error ({0}): {1}.
        /// </summary>
        public static string EXTERNAL_INTEGRATION_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_INTEGRATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ID is required..
        /// </summary>
        public static string ID_EMPTY {
            get {
                return ResourceManager.GetString("ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name must be between 2 and 100 characters..
        /// </summary>
        public static string NAME_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("NAME_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The neighborhood is required..
        /// </summary>
        public static string NEIGHBORHOOD_EMPTY {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The number is required..
        /// </summary>
        public static string NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Page number must be greater than or equal to 1..
        /// </summary>
        public static string PAGE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("PAGE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Page size must be between 1 and 100..
        /// </summary>
        public static string PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("PAGE_SIZE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The phone country code is invalid..
        /// </summary>
        public static string PHONE_COUNTRY_CODE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_COUNTRY_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The contact phone is required..
        /// </summary>
        public static string PHONE_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The phone number must be of valid length (between 8 and 20 digits)..
        /// </summary>
        public static string PHONE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The selected plan is invalid..
        /// </summary>
        public static string PLAN_INVALID {
            get {
                return ResourceManager.GetString("PLAN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The provided resource limits are invalid..
        /// </summary>
        public static string RESOURCE_LIMITS_INVALID {
            get {
                return ResourceManager.GetString("RESOURCE_LIMITS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The slug already exists..
        /// </summary>
        public static string SLUG_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SLUG_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The tenant slug cannot be empty..
        /// </summary>
        public static string SLUG_EMPTY {
            get {
                return ResourceManager.GetString("SLUG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The tenant slug must contain only lowercase letters, numbers, and hyphens, and cannot start or end with a hyphen..
        /// </summary>
        public static string SLUG_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("SLUG_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The tenant slug must be between 3 and 50 characters..
        /// </summary>
        public static string SLUG_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("SLUG_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The slug is a system reserved word..
        /// </summary>
        public static string SLUG_RESERVED {
            get {
                return ResourceManager.GetString("SLUG_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The state (UF) must be exactly 2 characters..
        /// </summary>
        public static string STATE_INVALID {
            get {
                return ResourceManager.GetString("STATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The state is required..
        /// </summary>
        public static string STATE_REQUIRED {
            get {
                return ResourceManager.GetString("STATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The street name is required..
        /// </summary>
        public static string STREET_EMPTY {
            get {
                return ResourceManager.GetString("STREET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The subscription end date cannot be earlier than the start date..
        /// </summary>
        public static string SUBSCRIPTION_END_DATE_INVALID {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_END_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The subscription is required..
        /// </summary>
        public static string SUBSCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trial subscriptions require a trial end date..
        /// </summary>
        public static string SUBSCRIPTION_TRIAL_END_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_TRIAL_END_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The suspension reason must be provided..
        /// </summary>
        public static string SUSPENSION_REASON_EMPTY {
            get {
                return ResourceManager.GetString("SUSPENSION_REASON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The suspension reason must be between 5 and 500 characters..
        /// </summary>
        public static string SUSPENSION_REASON_INVALID {
            get {
                return ResourceManager.GetString("SUSPENSION_REASON_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tenant not found..
        /// </summary>
        public static string TENANT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TENANT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only active or trialing tenants can be marked as past due..
        /// </summary>
        public static string TENANT_PAST_DUE_INVALID_STATUS {
            get {
                return ResourceManager.GetString("TENANT_PAST_DUE_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot deactivate an already terminated tenant..
        /// </summary>
        public static string TENANT_TERMINATED_CANNOT_DEACTIVATE {
            get {
                return ResourceManager.GetString("TENANT_TERMINATED_CANNOT_DEACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A terminated tenant cannot be reactivated..
        /// </summary>
        public static string TENANT_TERMINATED_CANNOT_REACTIVATE {
            get {
                return ResourceManager.GetString("TENANT_TERMINATED_CANNOT_REACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot suspend an already terminated tenant..
        /// </summary>
        public static string TENANT_TERMINATED_CANNOT_SUSPEND {
            get {
                return ResourceManager.GetString("TENANT_TERMINATED_CANNOT_SUSPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown Error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unknown error occurred in the CoreAuth API..
        /// </summary>
        public static string UNKNOWN_ERROR_CORE_AUTH {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR_CORE_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ZIP code must contain exactly 8 digits..
        /// </summary>
        public static string ZIPCODE_INVALID {
            get {
                return ResourceManager.GetString("ZIPCODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ZIP code is required..
        /// </summary>
        public static string ZIPCODE_REQUIRED {
            get {
                return ResourceManager.GetString("ZIPCODE_REQUIRED", resourceCulture);
            }
        }
    }
}
